### ISSUE TITLE
获取菜单选中项的时候有bug

### ISSUE THREAD

**Issue by goldencolor** [rookie0/AdminLTE_ThinkPHP#1]
第一个项永远是高亮

**Comment by rookie0** [comment]
好久之前写的了 不打算改了 ^O^ 
ace是收费的 建议换成[AdminLTE](https://github.com/almasaeed2010/AdminLTE)
active显示的话 之前是用递归去判断 有点复杂 其实把当前分类及父类做标识传给页面 用JS去设置就行
